aws_access_key = "..."
aws_secret_key = "..."
aws_region = "..."
aws_vpc_id = "..."
aws_subnet_id = "..."
aws_ssh_key_name = "..."
services_instance_type = "c4.2xlarge"
builder_instance_type = "r3.4xlarge"